### ISSUE TITLE
Description conflicts with licence

### ISSUE THREAD

**Issue by mchlbowyer** [eltima-software/USB-Web-Server#2]
In the description for this project it states 'If you want to distribute it as a part of your own non-Open Source software product, it's required to obtain appropriate license from Eltima Software (sales@eltima.com)' however the licence included with the project is a GNU General Public License v2.0 which allows for commercial use. Can you clarify which one is the correct licence?

**Comment by DorisLane** [comment]
Thank you! We have fixed the license information. Read more here https://github.com/eltima-software/USB-Web-Server/blob/master/LICENSE.md

**Comment by DorisLane** [comment]
Description fixed
